version: 2.0
jobs:
  build:
    working_directory: ~/hs-app-template
    docker:
      - image: fpco/stack-build:latest

    environment:
      LD_LIBRARY_PATH: /usr/local/lib

    steps:
      - checkout
      - restore_cache:
          keys: 
            - dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "hs-app-template.cabal" }}
            - dot-stack
      - restore_cache:
          key: stack-work-{{ checksum "stack.yaml" }}
      - restore_cache:
          key: librdkafka-{{ checksum "scripts/build-librdkafka.sh" }}

      - run:
          name: Build librdkafka
          command: ./scripts/build-librdkafka.sh

      - run: stack setup
      - run: stack build --test --no-run-tests 

      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Build the container
          command: ./scripts/container.sh build


      - run:
          name: Running unit tests
          command: stack test

      - save_cache:
          key: dot-stack-base
          paths:
            - ~/.stack

      - save_cache:
          key: dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "hs-app-template.cabal" }}
          paths:
            - ~/.stack

      - save_cache:
          key: stack-work-{{ checksum "stack.yaml" }}
          paths: ~/hs-app-template/.stack-work

      - save_cache:
          key: librdkafka-{{ checksum "scripts/build-librdkafka.sh" }}
          paths: ~/hs-app-template/.librdkafka

      - deploy:
          name: Pushing container
          command: ./scripts/container.sh push
